import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery, useQueryClient } from '@tanstack/react-query';
import { BrowserRouter, Link, Route, Routes, useNavigate } from 'react-router-dom';
import './style.css';

const queryClient = new QueryClient();
const headers = { 'content-type': 'application/json' };
async function api(path: string, options: RequestInit = {}) { const response = await fetch(path, { ...options, headers: { ...headers, ...(options.headers || {}) } }); if (!response.ok) throw new Error(`${response.status}`); return response.status === 204 ? null : response.json(); }
function Account({ setup = false }: { setup?: boolean }) { const [data, setData] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const submit = async (e: React.FormEvent) => { e.preventDefault(); await api(setup ? '/api/auth/setup' : '/api/auth/login', { method: 'POST', body: JSON.stringify(setup ? data : { email: data.email, password: data.password }) }); location.href = '/'; }; return <main><h1>MCP Firewall</h1><form onSubmit={submit}><h2>{setup ? 'Create Admin Account' : 'Admin login'}</h2>{(setup ? ['name', 'email', 'password', 'confirmPassword'] : ['email', 'password']).map((field) => <input key={field} aria-label={field} type={field.includes('password') ? 'password' : 'text'} placeholder={field} value={(data as any)[field]} onChange={(e) => setData({ ...data, [field]: e.target.value })} required />)}<button>{setup ? 'Create Admin Account' : 'Login'}</button>{!setup && <Link to="/setup">Create Admin Account</Link>}</form></main>; }
function Resource({ title, path }: { title: string; path: string }) { const qc = useQueryClient(); const query = useQuery({ queryKey: [path], queryFn: () => api(path) }); const [name, setName] = useState(''); const [target, setTarget] = useState(''); const mutate = async (url: string, method: string, body?: unknown) => { await api(url, { method, body: body ? JSON.stringify(body) : undefined }); await qc.invalidateQueries({ queryKey: [path] }); }; const create = (e: React.FormEvent) => { e.preventDefault(); mutate(path, 'POST', path.includes('policies') ? { name, match: { tool: target }, action: 'allow', enabled: true } : { name, transport: 'http', url: target }); }; return <section><h2>{title}</h2>{query.isLoading && <p>Loading</p>}{query.isError && <p role="alert">Error loading data</p>}<ul>{(query.data || []).map((item: any) => <li key={item.id || item.name}>{item.name || item.tool || item.id} <small>{item.action || item.status || item.decision}</small>{path === '/api/policies' && <><button onClick={() => mutate(`/api/policies/${encodeURIComponent(item.name)}`, 'PATCH', { enabled: !item.enabled })}>{item.enabled ? 'Disable' : 'Enable'}</button><button onClick={() => mutate(`/api/policies/${encodeURIComponent(item.name)}`, 'PATCH', { match: { tool: window.prompt('Tool match', item.match?.tool || '') || item.match?.tool }, action: window.prompt('Action', item.action || 'ALLOW') || item.action })}>Edit</button><button onClick={() => mutate(`/api/policies/${encodeURIComponent(item.name)}`, 'DELETE')}>Delete</button><details><summary>YAML</summary><pre>{`version: 1\npolicies:\n  - name: ${item.name}\n    match:\n      tool: ${item.match?.tool || ''}\n    action: ${String(item.action || '').toLowerCase()}\n    enabled: ${item.enabled}`}</pre></details></>}{path === '/api/mcp-servers' && <><button onClick={() => mutate(`/api/mcp-servers/${encodeURIComponent(item.name)}`, 'PATCH', { transport: item.transport, url: window.prompt('Server URL', item.url || '') || item.url })}>Edit</button><button onClick={() => mutate(`/api/mcp-servers/${encodeURIComponent(item.name)}`, 'DELETE')}>Delete</button></>}{path === '/api/approvals' && item.status === 'PENDING' && <><button onClick={() => mutate(`/api/approvals/${item.id}/approve`, 'POST', { approver: 'Admin' })}>Approve</button><button onClick={() => mutate(`/api/approvals/${item.id}/reject`, 'POST', { approver: 'Admin' })}>Reject</button></>}{path === '/api/audit-logs' && <details><summary>Details</summary><pre>{JSON.stringify(item, null, 2)}</pre></details>}</li>)}</ul>{(path === '/api/policies' || path === '/api/mcp-servers') && <form onSubmit={create}><input aria-label="Name" placeholder="Name" value={name} onChange={(e) => setName(e.target.value)} required /><input aria-label="Target" placeholder="Tool or URL" value={target} onChange={(e) => setTarget(e.target.value)} required /><button>{path === '/api/policies' ? 'Create policy' : 'Add MCP Server'}</button></form>}</section>; }
function Dashboard() { const nav = useNavigate(); const audit = useQuery({ queryKey: ['/api/audit-logs'], queryFn: () => api('/api/audit-logs') }); const events = audit.data || []; const counts = events.reduce((all: any, event: any) => ({ ...all, [event.tool]: (all[event.tool] || 0) + 1 }), {}); const secrets = events.filter((event: any) => JSON.stringify(event.arguments).includes('[REDACTED]')).length; return <main><header><h1>MCP Firewall Command Center</h1><button onClick={() => api('/api/auth/logout', { method: 'POST' }).then(() => nav('/login'))}>Logout</button></header><p>Total Tool Calls: {events.length} · Allowed: {events.filter((x: any) => x.decision === 'ALLOW').length} · Blocked: {events.filter((x: any) => x.decision === 'DENY').length} · Requires Approval: {events.filter((x: any) => x.decision === 'REQUIRE_APPROVAL').length} · Secrets Intercepted: {secrets}</p><p>Most Used Tools: {Object.entries(counts).sort(([, a]: any, [, b]: any) => b - a).slice(0, 5).map(([tool, count]) => `${tool} (${count})`).join(', ') || 'None'}</p><nav><Link to="/">Dashboard</Link><Link to="/policies">Policies</Link><Link to="/servers">MCP Servers</Link><Link to="/approvals">Approvals</Link><Link to="/audit-logs">Audit Logs</Link></nav><Routes><Route path="/policies" element={<Resource title="Policies" path="/api/policies" />} /><Route path="/servers" element={<Resource title="MCP Servers" path="/api/mcp-servers" />} /><Route path="/approvals" element={<Resource title="Approvals" path="/api/approvals" />} /><Route path="/audit-logs" element={<Resource title="Audit Logs" path="/api/audit-logs" />} /><Route path="*" element={<><Resource title="Active Policies" path="/api/policies" /><h2>Activity Timeline</h2><pre>{JSON.stringify(events.slice(-10), null, 2)}</pre></>} /></Routes></main>; }
function App() { return <Routes><Route path="/login" element={<Account />} /><Route path="/setup" element={<Account setup />} /><Route path="*" element={<Dashboard />} /></Routes>; }
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><BrowserRouter><App /></BrowserRouter></QueryClientProvider>);
