import { test, expect } from '@playwright/test';
test('dashboard route is reachable', async ({ page }) => { await page.goto('/api/dashboard?view=login'); await expect(page).toHaveTitle(/Login|MCP Firewall/); });
test('admin command center exposes resource views', async ({ page }) => { await page.goto('/'); await expect(page.getByText('MCP Firewall')).toBeVisible(); await expect(page.getByRole('link', { name: 'Policies' })).toBeVisible(); await expect(page.getByRole('link', { name: 'MCP Servers' })).toBeVisible(); await expect(page.getByRole('link', { name: 'Approvals' })).toBeVisible(); await expect(page.getByRole('link', { name: 'Audit Logs' })).toBeVisible(); });
test('setup and login surfaces expose the complete admin flow', async ({ page }) => { await page.goto('/setup'); await expect(page.getByRole('heading', { name: 'Create Admin Account' })).toBeVisible(); await expect(page.getByLabel('name')).toBeVisible(); await expect(page.getByLabel('confirmPassword')).toBeVisible(); await page.goto('/login'); await expect(page.getByRole('heading', { name: 'Admin login' })).toBeVisible(); await expect(page.getByLabel('email')).toBeVisible(); await expect(page.getByLabel('password')).toBeVisible(); });
test('dashboard exposes timeline and most-used-tools sections after authentication', async ({ page }) => { await page.route('/api/audit-logs', async route => route.fulfill({ json: [{ id: 'e1', tool: 'filesystem.read', decision: 'ALLOW', created_at: 'now', arguments: {} }] })); await page.goto('/'); await expect(page.getByText('Activity Timeline')).toBeVisible(); await expect(page.getByText('Most Used Tools')).toBeVisible(); await expect(page.getByText('filesystem.read · 1 calls')).toBeVisible(); });
test('authenticated admin performs policy/server CRUD, approval review, audit inspection and logout', async ({ page }) => {
  const suffix = Date.now().toString(); const email = `e2e-${suffix}@example.test`; const password = 'E2e-password-123!';
  const setup = await page.request.post('/api/auth/setup', { data: { name: 'E2E Admin', email, password, confirmPassword: password } }); expect(setup.ok()).toBeTruthy();
  const login = await page.request.post('/api/auth/login', { data: { email, password } }); expect(login.ok()).toBeTruthy();
  await page.goto('/policies'); await page.getByLabel('Name').fill(`e2e-policy-${suffix}`); await page.getByLabel('Target').fill('e2e.read'); await page.getByRole('button', { name: 'Create policy' }).click(); await expect(page.getByText(`e2e-policy-${suffix}`)).toBeVisible();
  await page.goto('/servers'); await page.getByLabel('Name').fill(`e2e-server-${suffix}`); await page.getByLabel('Target').fill('http://127.0.0.1:9'); await page.getByRole('button', { name: 'Add MCP Server' }).click(); await expect(page.getByText(`e2e-server-${suffix}`)).toBeVisible();
  const approvalPolicy = await page.request.post('/api/policies', { data: { name: `e2e-approval-${suffix}`, match: { tool: `e2e.approve.${suffix}` }, action: 'require_approval', enabled: true } }); expect(approvalPolicy.ok()).toBeTruthy();
  const approvalCall = await page.request.post('/mcp/tools/call', { data: { tool: `e2e.approve.${suffix}`, arguments: { password: 'secret-value' } } }); expect(approvalCall.status()).toBe(202);
  await page.goto('/approvals'); await expect(page.getByText('PENDING')).toBeVisible(); await page.getByRole('button', { name: 'Reject' }).click();
  await page.goto('/audit-logs'); await expect(page.getByText('Details')).toBeVisible(); await page.getByRole('button', { name: 'Logout' }).click(); await expect(page).toHaveURL(/login/);
});
